openapi: 3.0.1
info:
  title: .WebAPI
  version: "1.0"
servers:
  - url: https://sandbox.solutra.com.br/Solutra/Auth/
paths:
  /auth/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginQuery"
          text/json:
            schema:
              $ref: "#/components/schemas/LoginQuery"
          application/*+json:
            schema:
              $ref: "#/components/schemas/LoginQuery"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginQueryResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationProblemDetails"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /auth/refreshtoken:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenQuery"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshTokenQueryResponse"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    LoginQuery:
      type: object
      properties:
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    LoginQueryResponse:
      type: object
      properties:
        token:
          type: string
          nullable: true
        tokenExpiration:
          type: string
          format: date-time
        refreshToken:
          type: string
          nullable: true
        refreshTokenExpiration:
          type: string
          format: date-time
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    RefreshTokenQuery:
      type: object
      properties:
        refreshToken:
          type: string
          nullable: true
      additionalProperties: false
    RefreshTokenQueryResponse:
      type: object
      properties:
        token:
          type: string
          nullable: true
        tokenExpiration:
          type: string
          format: date-time
        refreshToken:
          type: string
          nullable: true
        refreshTokenExpiration:
          type: string
          format: date-time
      additionalProperties: false
    ValidationProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          nullable: true
          readOnly: true
      additionalProperties: {}
